var texture, texture2, texture3, textureRight, zebraTexture, zebraTexture2, stippelTexture, geleborduurTexture, busTexture, golfTexture, kinderKopTexture, voetpadTexture;
var imgTexture2, imgTexture;
var dalTexture;
var tile1Texture, tile2Texture, tile3Texture, tile4Texture, tile5Texture;
var tileTextures = [];
var maxAnisotropy;
function addTexture(fileName) {
	var newTexture = THREE.ImageUtils.loadTexture(fileName);
	newTexture.anisotropy = maxAnisotropy;
	return newTexture;
}
function addTextures() {
	maxAnisotropy = renderer.getMaxAnisotropy();
	//texture = THREE.ImageUtils.loadTexture('textures/road4.gif');
	//texture.anisotropy = renderer.getMaxAnisotropy();
	texture = addTexture('textures/zwart.jpg');
	//texture2 = THREE.ImageUtils.loadTexture('textures/corner5.gif');
	//texture2.anisotropy = renderer.getMaxAnisotropy();
	texture2 = addTexture('textures/corner5.gif');
	//texture3 = THREE.ImageUtils.loadTexture('textures/stippel.jpg');
	//texture3.anisotropy = renderer.getMaxAnisotropy();
	texture3 = addTexture('textures/stippel.jpg');
	texture3.wrapT = THREE.RepeatWrapping;
	texture3.repeat.set(1, 9);
	//textureRight = THREE.ImageUtils.loadTexture('textures/right.gif');
	//textureRight.anisotropy = renderer.getMaxAnisotropy();
	textureRight = addTexture('textures/right.gif');
	//zebraTexture = THREE.ImageUtils.loadTexture('textures/zebra.gif');
	//zebraTexture.anisotropy = renderer.getMaxAnisotropy();
	zebraTexture = addTexture('textures/zebra.gif');
	//zebraTexture2 = THREE.ImageUtils.loadTexture('textures/zebra2.jpg');
	//zebraTexture2.anisotropy = renderer.getMaxAnisotropy();
	zebraTexture2 = addTexture('textures/zebra2.jpg');
	zebraTexture2.wrapH = zebraTexture2.wrapS = THREE.RepeatWrapping;
	zebraTexture2.repeat.set(8, 1);
	//stippelTexture = THREE.ImageUtils.loadTexture('textures/stippel.jpg');
	//stippelTexture.anisotropy = renderer.getMaxAnisotropy();
	stippelTexture = addTexture('textures/stippel.jpg');
	//stippelTexture.wrapS = THREE.RepeatWrapping;
	stippelTexture.wrapH = stippelTexture.wrapS = stippelTexture.wrapT = THREE.RepeatWrapping;
	stippelTexture.repeat.set(1, 6);
	//geleborduurTexture = THREE.ImageUtils.loadTexture('textures/geleborduur.gif');
	//geleborduurTexture.anisotropy = renderer.getMaxAnisotropy();
	geleborduurTexture = addTexture('textures/geleborduur.gif');
	geleborduurTexture.wrapT = THREE.RepeatWrapping;
	geleborduurTexture.wrapS = THREE.RepeatWrapping;
	geleborduurTexture.repeat.set(1, 18);
	//busTexture = THREE.ImageUtils.loadTexture('textures/bus.gif');
	//busTexture.anisotropy = renderer.getMaxAnisotropy();
	busTexture = addTexture('textures/bus.gif');
	//golfTexture = THREE.ImageUtils.loadTexture('textures/golf.png');
	//golfTexture.anisotropy = renderer.getMaxAnisotropy();
	golfTexture = addTexture('textures/golf.png');
	//kinderKopTexture = THREE.ImageUtils.loadTexture('textures/kinderkop.jpg');
	//kinderKopTexture.anisotropy = renderer.getMaxAnisotropy();
	kinderKopTexture = addTexture('textures/kinderkop.jpg');
	kinderKopTexture.wrapT = THREE.RepeatWrapping;
	kinderKopTexture.wrapS = THREE.RepeatWrapping;
	kinderKopTexture.repeat.set(1, 1);
	//voetpadTexture = THREE.ImageUtils.loadTexture('textures/voetpad.gif');
	//voetpadTexture.anisotropy = renderer.getMaxAnisotropy();
	voetpadTexture = addTexture('textures/voetpad.gif');
	//stippelTexture.wrapS = THREE.RepeatWrapping;
	voetpadTexture.wrapT = THREE.RepeatWrapping;
	voetpadTexture.repeat.set(4, 4);
	//imgTexture2 = THREE.ImageUtils.loadTexture("obj/gevel/baksteen3.jpg");
	//imgTexture2.wrapS = imgTexture2.wrapT = THREE.RepeatWrapping;
	imgTexture2 = addTexture('obj/gevel/baksteen3.jpg');
	//imgTexture2.anisotropy = 16;
	//imgTexture = THREE.ImageUtils.loadTexture('obj/gevel/baksteen3.jpg');
	//imgTexture.anisotropy = 16;
	//imgTexture = addTexture('textures/gino.png');
	imgTexture = addTexture('obj/gevel/baksteen3.jpg');
	imgTexture.repeat.set(32, 32);
	//imgTexture.repeat.set(1, 1);
	imgTexture.wrapS = imgTexture.wrapT = THREE.RepeatWrapping;
	dalTexture = addTexture('textures/dal2.jpg');
	dalTexture.repeat.set(3, 16);
	dalTexture.wrapS = dalTexture.wrapT = THREE.RepeatWrapping;
	/*tile1Texture = addTexture('tiles/152453.9194765,221879.38761306,152462.45078472,221887.91892127.png');
	tile2Texture = addTexture('tiles/152436.85686006,221896.45022949,152445.38816828,221904.98153771.png');
	tile3Texture = addTexture('tiles/152462.45078472,221896.45022949,152470.98209294,221904.98153771.png');
	tile4Texture = addTexture('tiles/152453.9194765,221862.32499662,152462.45078472,221870.85630484.png');
	tile5Texture = addTexture('tiles/152428.32555184,221896.45022949,152445.38816828,221913.51284593.png');*/
}